/**
 * Script that generates workflow-generated.ts from workflow-paste.ts
 * 
 * This script reads the raw workflow-paste.ts (with NO exports) and generates
 * workflow-generated.ts with proper exports added.
 * 
 * Run: npx tsx scripts/generate-workflow.ts
 * Or add to package.json scripts
 */

import * as fs from 'fs';
import * as path from 'path';

const workflowPastePath = path.join(__dirname, '../agents/workflow-paste.ts');
const workflowGeneratedPath = path.join(__dirname, '../agents/workflow-generated.ts');

// Read the raw workflow file
const rawContent = fs.readFileSync(workflowPastePath, 'utf-8');

// Function to add export keyword before a declaration
function addExport(content: string, pattern: RegExp, exportKeyword: string = 'export'): string {
  // Check if already has export
  if (pattern.test(content)) {
    // Check if it already has export
    const withExportPattern = new RegExp(`export\\s+${pattern.source.replace(/^\\^/, '').replace(/\\$$/, '')}`);
    if (withExportPattern.test(content)) {
      return content; // Already exported
    }
    
    // Add export before the declaration
    return content.replace(pattern, (match) => {
      // Don't add export if it's already there or if it's in a comment
      if (match.includes('export')) return match;
      return `${exportKeyword} ${match}`;
    });
  }
  return content;
}

// Patterns to find and export
let generatedContent = rawContent;

// 1. Find and export myAgent (or agent, mainAgent, etc.)
// Look for: const myAgent = new Agent({ or const agent = new Agent({
const agentPatterns = [
  /(const\s+myAgent\s*=\s*new\s+Agent\()/,
  /(const\s+agent\s*=\s*new\s+Agent\()/,
  /(const\s+mainAgent\s*=\s*new\s+Agent\()/,
];

let agentFound = false;
for (const pattern of agentPatterns) {
  if (pattern.test(generatedContent) && !generatedContent.includes('export const myAgent') && !generatedContent.includes('export const agent')) {
    generatedContent = generatedContent.replace(pattern, 'export $1');
    agentFound = true;
    break;
  }
}

if (!agentFound) {
  console.warn('⚠️  Could not find agent declaration. Looking for: const myAgent = new Agent({ or const agent = new Agent({');
}

// 2. Find and export WorkflowInput type
const typePatterns = [
  /(type\s+WorkflowInput\s*=)/,
  /(interface\s+WorkflowInput)/,
];

let typeFound = false;
for (const pattern of typePatterns) {
  if (pattern.test(generatedContent) && !generatedContent.includes('export type WorkflowInput') && !generatedContent.includes('export interface WorkflowInput')) {
    generatedContent = generatedContent.replace(pattern, 'export $1');
    typeFound = true;
    break;
  }
}

if (!typeFound) {
  console.warn('⚠️  Could not find WorkflowInput type. Looking for: type WorkflowInput = or interface WorkflowInput');
  // Add a default if not found
  if (!generatedContent.includes('WorkflowInput')) {
    generatedContent = `export type WorkflowInput = { input_as_text: string };\n\n${generatedContent}`;
  }
}

// 3. Find and export runWorkflow function (or workflow, executeWorkflow, etc.)
const workflowPatterns = [
  /(const\s+runWorkflow\s*=\s*async\s*\()/,
  /(const\s+workflow\s*=\s*async\s*\()/,
  /(const\s+executeWorkflow\s*=\s*async\s*\()/,
  /(async\s+function\s+runWorkflow\s*\()/,
  /(async\s+function\s+workflow\s*\()/,
];

let workflowFound = false;
for (const pattern of workflowPatterns) {
  if (pattern.test(generatedContent) && !generatedContent.includes('export const runWorkflow') && !generatedContent.includes('export async function runWorkflow')) {
    generatedContent = generatedContent.replace(pattern, 'export $1');
    workflowFound = true;
    break;
  }
}

if (!workflowFound) {
  console.warn('⚠️  Could not find workflow function. Looking for: const runWorkflow = async( or async function runWorkflow(');
}

// Add header comment
const header = `/**
 * AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY
 * 
 * This file is automatically generated from workflow-paste.ts
 * It adds the necessary exports so other files can import from it.
 * 
 * To regenerate: npx tsx scripts/generate-workflow.ts
 * 
 * The source file (workflow-paste.ts) has NO exports - it's completely raw.
 * This file adds the exports needed for TypeScript imports.
 */

`;

generatedContent = header + generatedContent;

// Write the generated file
fs.writeFileSync(workflowGeneratedPath, generatedContent, 'utf-8');

console.log('✅ Generated workflow-generated.ts from workflow-paste.ts');
console.log(`   - Agent found: ${agentFound ? '✅' : '❌'}`);
console.log(`   - Type found: ${typeFound ? '✅' : '❌'}`);
console.log(`   - Workflow found: ${workflowFound ? '✅' : '❌'}`);

